# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1573afc9b5a48f710ae5056fecac50c4b2a0bafcf72e9369f7cff53eb78bd75f271fc4b420a58e666921078de4a08f21d7153359042b60388474118096c2eb5a

test:
  secret_key_base: 66f7fada2d39dcd7f5dd7a5e02807fab4dfed2284893bda0ed8c0d48e4f5b65055bd799fbfb9d9cfe4800fce23a4567ae705afc1006b2953a51bd687076c31af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
